// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4mM2Wfro6aHMdU2FfI9tb0A3a_GiCsE',
    appId: '1:417024060421:web:151405974eb0c9ed11406c',
    messagingSenderId: '417024060421',
    projectId: 'flutter-chatapp-58c7e',
    authDomain: 'flutter-chatapp-58c7e.firebaseapp.com',
    storageBucket: 'flutter-chatapp-58c7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdo-_KMZiC41YmDNYhAgTn6aA92Sg45VA',
    appId: '1:417024060421:android:f8018faa93735dca11406c',
    messagingSenderId: '417024060421',
    projectId: 'flutter-chatapp-58c7e',
    storageBucket: 'flutter-chatapp-58c7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBZGRqTTiLFmjSNCqvdT6fiVDTzJ1Mx0',
    appId: '1:417024060421:ios:6617906b2178652b11406c',
    messagingSenderId: '417024060421',
    projectId: 'flutter-chatapp-58c7e',
    storageBucket: 'flutter-chatapp-58c7e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
